core/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path
from guest_book import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),
    path('add', views.add_guest, name='add'),
    path('edit<int:id>', views.edit_guest, name='edit'),
    path('<int:id>', views.delete_guest, name='delete')
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

guest_book/models.py
from django.db import models


class Guest_book(models.Model):
    name = models.CharField(
        max_length=500,
        null=False,
        blank=False,
        verbose_name='Name'
    )
    email_author = models.EmailField(
        max_length=254,
        null=False,
        blank=False,
        verbose_name='Email'
    )
    entry_text = models.TextField(
        max_length=5000,
        null=False,
        blank=False,
        verbose_name='Entry text'
    )
    time_of_creation = models.DateTimeField(
        auto_now_add=True,
        null=False,
        blank=False,
        verbose_name='Time of creations'
    )
    edit_time = models.DateTimeField(
        auto_now=True,
        null=False,
        blank=False,
        verbose_name='Edit time'
    )

    STATUS_CHOICES = [
        ('active', 'Активно'),
        ('blocked', 'Заблокировано')
    ]
    status = models.CharField(
        max_length=10,
        choices=STATUS_CHOICES, default='active',
        null=False,
        blank=False,
        verbose_name='Status'
    )

    def __str__(self):
        return self.name
# Create your models here.

guest_book/forms.py
from django import forms
from .models import Guest_book


class GuestForms(forms.ModelForm):
    name = forms.CharField(required=True)

    class Meta:
        model = Guest_book
        fields = ['name', 'email_author', 'entry_text']


class SearchForm(forms.Form):
    name = forms.CharField(label='Author Name', max_length=250)

guest_book/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Guest_book
from .forms import GuestForms, SearchForm
# Create your views here.

def home(request):
    form = SearchForm()
    guest = Guest_book.objects.filter(status='active').order_by('-time_of_creation')

    if request.method == 'POST':
        form = SearchForm(request.POST)
        if form.is_valid():
            name = form.cleaned_data['name']
            guest = guest.filter(name=name)
        return render(request, 'home.html', context={'guest': guest, 'form': form})
    else:
        return render(request, 'home.html', context={'guest': guest, 'form': form})



def add_guest(request):
    if request.method == 'POST':
        print(request.POST)
        form = GuestForms(request.POST)
        if form.is_valid():
            form.save()
            return redirect('home')
    else:
        form = GuestForms
    return render(request, 'add_guest.html', {'form': form})


def edit_guest(request, id):
    guest = get_object_or_404(Guest_book, id=id)
    if request.method == 'GET':
        form = GuestForms(instance=guest)
        return render(request, 'edit_guest.html', {'guest': guest, 'form': form})
    elif request.method == 'POST':
        form = GuestForms(data=request.POST, instance=guest)
        if form.is_valid():
            form.save()
            return redirect('home')
        else:
            return render(request, 'edit_guest.html', {'guest': guest, 'form': form})


def delete_guest(request, id):
    guest = get_object_or_404(Guest_book, id=id)
    guest.delete()
    return redirect('home')

guest_book/templates/add_guest.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
  <h1>Add Guest</h1>
  {% include 'form/guest_form.html' with text_button='Add' %}

{% endblock %}

guest_book/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.0.1/css/bootstrap.min.css" integrity="sha512-Ez0cGzNzHR1tYAv56860NLspgUGuQw16GiOOp/I2LuTmpSK9xDXlgJz3XN4cnpXWDmkNBKXR/VDMTCnAaEooxA==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.3.0/font/bootstrap-icons.css">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <title>Title</title>
</head>
<body class="bg-success bg-opacity-75 text-white">
<nav class="navbar navbar-expand-lg navbar-light bg-light mb-3">
  <div class="container-fluid">
    <a class="navbar-brand" href="{% url 'home' %}">MG</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link" aria-current="page" href={% url 'home' %}>Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href={% url 'add' %}>Add new guest</a>
        </li>
      </ul>
    </div>
  </div>
</nav>

   <div class="project_body container">
        {% block content %} {% endblock %}

    </div>
<script src="{% static 'js/scripts.js' %}"></script>
</body>
</html>

guest_book/templates/edit_guest.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
  <h1>Edit Guest</h1>
  {% include 'form/guest_form.html' with text_button='Edit' %}
    <br/>

{% endblock %}

guest_book/templates/form/guest_form.html
<form method="post">

  {% csrf_token %}
<hr>
  {{ form.non_field_errors }}
  <label for="id_name">Name:</label>
  <input type="text" name="name" id="id_name" class="form-control {% if form.errors %}is-invalid{% endif %} mb-2" value="{{ guest.name }}">
{% if form.errors %}
      <div class="invalid-feedback">
        {{ form.name.errors|join:"" }}
      </div>
    {% endif %}
  <label for="id_entry_text">Email:</label>
  <input type="email" name="email_author" id="id_entry_text" class="form-control  {% if form.name.errors %}is-invalid{% endif %} mb-2" value="{{ guest.email_author }}">
{% if form.email_author.errors %}
      <div class="invalid-feedback">
        {{ form.email_author.errors|join:" " }}
      </div>
    {% endif %}
  <label for="id_text">Text:</label><br/>
  <textarea name="entry_text" id="id_text" class="form-control {% if form.entry_text.errors %}is-invalid{% endif %} mb-2">{{ guest.entry_text }}</textarea>
{% if form.entry_text.errors %}
      <div class="invalid-feedback">
        {{ form.entry_text.errors|join:" " }}
      </div>
    {% endif %}
    <button type="submit" class="btn btn-info text-white mt-3">{{ text_button }}</button>

</form>

guest_book/templates/home.html
{% extends 'base.html' %}
{% block content %}
    <form method="post">
    {% csrf_token %}
        <div class="mb-3">
            <label for="id_name">Name author: </label>
        <input type="text" name="name" id="id_name" class="form-control">
        <button class="btn btn-info text-white mt-3" type="submit">Find</button>
        </div>
    {% for gue in guest %}
<div class="row">
  <div class="col mb-3">
    <div class="card text-dark" style="border-radius: 20px">
      <div class="card-body">
        <h5 class="card-title d-flex justify-content-between">{{ gue.name }} ({{ gue.email_author }})
            <div>
                <a href="{% url 'delete' id=gue.id %}" class="link-decoration"><i class="bi bi-file-earmark-minus" onclick="return confirmDelete()"></i></a>
                <a href="{% url 'edit' id=gue.id %}" class="link-decoration"><i class="bi bi-pencil-square"></i></a>
            </div>
        </h5>
        <p class="card-text">{{ gue.entry_text }}</p>
      </div>
    </div>
  </div>
</div>
{% endfor %}
    </form>

{% endblock %}